targets:
  $default:
    builders:
      # auto_route
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/features/**_page.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/shared/config/routes/**_router.dart
      # json_serializable
      json_serializable:
        options:
          explicit_to_json: true
