name: sumeer
description: Sumeer - Resume builder mobile application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  path_provider: ^2.0.15
  dartz: ^0.10.1
  uuid: ^3.0.7
  equatable: ^2.0.5
  flutter_displaymode: ^0.6.0
  logger: ^2.0.1
  collection: ^1.17.1
  auto_route: ^7.7.1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_dotenv: ^5.1.0
  form_field_validator: ^1.1.0

  pdf: ^3.10.4
  pdf_render: ^1.4.0
  printing: ^5.11.0
  buttons_tabbar: ^1.3.7+1
  flutter_pdfview: ^1.3.1

  google_fonts: ^5.1.0
  freezed_annotation: ^2.4.1
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.7
  onboarding_animation: ^0.0.3

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  firebase_crashlytics: ^3.3.4
  riverpod_annotation: ^2.1.1
  firebase_ui_auth: ^1.6.1
  firebase_ui_oauth_google: ^1.2.6

  circular_profile_avatar: ^2.0.5
  flutter_holo_date_picker: ^1.1.0
  json_annotation: ^4.8.1
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3
  searchfield: ^0.8.3
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.4.3
  external_path: ^1.0.3
  rabbit_converter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  auto_route_generator: ^7.2.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/resume/
    - assets/images/onboarding/
    - assets/images/templates/
    - assets/images/home/
    - assets/fonts/
    - assets/www/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts: derry.yaml

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/\w+\.\w+\.dart
