name: sumeer
description: Sumeer - Resume builder mobile application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  path_provider: ^2.0.15
  dartz: ^0.10.1
  uuid: ^3.0.7
  equatable: ^2.0.5
  flutter_displaymode: ^0.6.0
  logger: ^1.4.0
  collection: ^1.17.1
  auto_route: ^7.7.1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_dotenv: ^5.1.0

  pdf: ^3.10.4
  pdf_render: ^1.4.0
  printing: ^5.11.0

  google_fonts: ^5.1.0
  freezed_annotation: ^2.4.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  auto_route_generator: ^7.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/resume/
    - assets/images/templates/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts: derry.yaml

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/\w+\.\w+\.dart
