name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "17"
      FLUTTER_VERSION: "3.x"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - run: flutter pub get
      - run: dart run build_runner build -d
      - run: flutter analyze
      # - run: flutter test
