name: Flutter CI Android

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    name: Check Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          # flutter-version: "3.7.7"
          cache: true
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: dart run build_runner build -d
      - run: flutter test
