name: Android Release Develop

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    name: Create Android build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          # flutter-version: "3.7.7"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
