name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pull-requests: write
      issues: read
      packages: none
    env:
      JAVA_VERSION: "17"
      FLUTTER_VERSION: "3.x"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: "stable"
      - run: flutter pub get
      - run: dart run build_runner build -d
      - run: flutter analyze
      # - run: flutter test
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
